# Generated by Django 5.1.5 on 2025-05-09 08:55

from django.db import migrations
from users.models import Role


def populate_role(apps, schema_editor):
    Role.get_student()
    Role.get_club()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(populate_role)]
