# Generated by Django 5.1.5 on 2025-05-09 09:01

from django.db import migrations


def create_event_types(apps, schema_editor):
    EventType = apps.get_model("events", "EventType")
    types = [
        "Conference",
        "Workshop",
        "Social & Human Rights",
        "Event Support",
        "Sport",
        "Education",
        "Arts & Culture",
        "Science & Technology",
        "Health & Wellness",
        "Environment & Sustainability",
        "Business & Entrepreneurship",
        "Community Service",
        "Networking",
        "Career Development",
        "Travel & Adventure",
        "Food & Drink",
    ]
    for type_name in types:
        EventType.objects.get_or_create(name=type_name)


def reverse_event_types(apps, schema_editor):
    EventType = apps.get_model("events", "EventType")
    EventType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0001_initial",
        ),  # убедись, что зависимость соответствует твоей последней миграции
    ]

    operations = [
        migrations.RunPython(create_event_types, reverse_event_types),
    ]
