# Generated by Django 5.1.5 on 2025-05-10 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicModelConfig',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('app_label', models.CharField(max_length=128)),
                ('model_name', models.CharField(max_length=128)),
                ('verbose_name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('action_type', models.IntegerField(choices=[(0, 'Create'), (1, 'Modify'), (2, 'Delete')], default=0, verbose_name='Action type')),
                ('recording_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='Record to apply')),
                ('model', models.CharField(default='', max_length=1000, verbose_name='Where stored')),
                ('previous_data', models.JSONField(null=True, verbose_name='Previous data')),
                ('new_data', models.JSONField(null=True, verbose_name='New data')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author of action')),
            ],
            options={
                'verbose_name': 'Action history',
                'verbose_name_plural': 'Actions history',
            },
        ),
    ]
